# Generated by Django 3.2.6 on 2025-02-06 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('sr_no', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('pin_code', models.CharField(max_length=10)),
                ('distance_km', models.FloatField()),
            ],
        ),
    ]
