# Generated by Django 3.2.6 on 2025-02-06 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20250206_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='city',
            field=models.CharField(default='11:23', max_length=100),
            preserve_default=False,
        ),
    ]
