# Generated by Django 3.2.6 on 2025-02-06 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_hospital_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='sr_no',
        ),
        migrations.AddField(
            model_name='hospital',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospital',
            name='location_link',
            field=models.URLField(default='01'),
            preserve_default=False,
        ),
    ]
